INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3727, 'ALMONDS','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3715, 'ANCONA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'ARCHERTON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3670, 'BADDAGINNIE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'BARJARG','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3722, 'BARWITE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3747, 'BEECHWORTH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3671, 'BENALLA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3672, 'BENALLA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'BOBINAWARRAH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3720, 'BONNIE DOON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'BOORHAMAN','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'BOORHAMAN EAST','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'BOOROLITE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'BOWEYA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'BOWEYA NORTH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'BOWSER','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3725, 'BOXWOOD','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'BRIDGE CREEK','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3741, 'BRIGHT','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'BROKEN CREEK','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3726, 'BUNGEET','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3726, 'BUNGEET WEST','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'BYAWATHA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'CARBOOR','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'CHESHUNT','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'CHESHUNT SOUTH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3725, 'CHESNEY VALE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'DELATITE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3726, 'DEVENISH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'DOCKER','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'DOCKERS PLAINS','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'EAST WANGARATTA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'EDI','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'EDI UPPER','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3746, 'ELDORADO','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'ENOCHS POINT','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3666, 'EUROA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'EVERTON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'EVERTON UPPER','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'GAFFNEYS CREEK','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'GLENROWAN','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'GLENROWAN WEST','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'GOOMALIBEE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3725, 'GOORAMBAT','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'GOUGHS BAY','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'GRETA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'GRETA SOUTH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'GRETA WEST','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'HANSONVILLE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'HOWES CREEK','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'HOWQUA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'HOWQUA HILLS','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'HOWQUA INLET','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'JAMIESON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'KEVINGTON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'KILLAWARRA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'KING VALLEY','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'KNOCKWOOD','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'LACEBY','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3727, 'LAKE ROWAN','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'LIMA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'LIMA EAST','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'LIMA SOUTH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'LONDRIGAN','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'LURG','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'MACS COVE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'MAINDAMPLE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3725, 'MAJOR PLAINS','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3722, 'MANSFIELD','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3724, 'MANSFIELD','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'MARKWOOD','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'MATLOCK','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'MERRIJIG','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3715, 'MERTON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3678, 'MILAWA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3722, 'MIRIMBAH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'MOLYULLAH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'MOORNGAG','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3699, 'MOUNT BEAUTY','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'MOUNT BRUNO','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3723, 'MOUNT BULLER','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3732, 'MOYHU','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3610, 'MURCHISON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3610, 'MURCHISON EAST','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3610, 'MURCHISON NORTH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3747, 'MURMUNGEE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3732, 'MYRRHEE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3737, 'MYRTLEFORD','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3727, 'PELLUEBLA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'SAMARIA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3727, 'ST JAMES','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3747, 'STANLEY','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3725, 'STEWARTON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'SWANPOOL','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3675, 'TAMINICK','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3670, 'TARNOOK','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'TATONG','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3726, 'THOONA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'UPPER LURG','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'UPPER RYANS CREEK','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3676, 'WANGARATTA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3677, 'WANGARATTA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3670, 'WARRENBAYNE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3733, 'WHITFIELD','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'WINTON','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3673, 'WINTON NORTH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3715, 'WOODFIELD','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3747, 'WOORAGEE','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3749, 'YACKANDANDAH','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3677, 'YARRUNGA','VIC', 'www.northeastvictorianjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3727, 'YUNDOOL','VIC', 'www.northeastvictorianjobs.com.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Alexandra','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Alligator Creek','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Andergrove','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4737, 'Armstrong Beach','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Bakers Creek','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Balberra','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Ball Bay','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Balnagowan','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Beaconsfield','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Belmunda','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4754, 'Benholme','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Blacks Beach','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4799, 'Bloomsbury','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Brightly','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4757, 'Broken River','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4750, 'Bucasia','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4798, 'Calen','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4737, 'Campwin Beach','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Cape Hillsborough','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Chelona','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4737, 'Colston Park','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Conignsby','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4757, 'Crediton','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Cremorne','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4757, 'Dalrymple Heights','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4753, 'Devereux Creek','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Dolphin Heads','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4754, 'Dows Creek','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Dumbleton','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Dundula','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Dunnrock','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'East Mackay','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Eimeo','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Erakala','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Eton','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Eton North','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4757, 'Eungella','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4757, 'Eungella Dam','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Eungella Hinterland','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Farleigh','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4756, 'Finch Hatton','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Foulden','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4737, 'Freshwater Point','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Gargett','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Glenella','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Grasstree Beach','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4751, 'Greenmount','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Habana','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Haliday Bay','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Hampden','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Hay Point','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Hazledean','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Homebush','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Kinchant Dam','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4738, 'Koumala','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Kuttabul','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4800, 'Laguna Quays','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Mackay','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Mackay Harbour','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4753, 'Marian','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Mcewens Beach','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4798, 'Mentmore','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4754, 'Mia Mia','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4799, 'Midge Point','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4754, 'Mirani','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Mount Charlton','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Mount Jukes','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4754, 'Mount Martin','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Mount Ossa','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Mount Pleasant','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Mt Pelion','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Munbura','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4756, 'Netherdale','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Nindaroo','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'North Mackay','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Oakenden','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Ooralea','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Owens Creek','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Paget','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4751, 'Palmyra','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4798, 'Pindi Pindi','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4754, 'Pinevale','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Pinnacle','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Pleystowe','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Racecourse','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Richmond','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Rosella','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Rural View','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Sandiford','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4737, 'Sarina','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4737, 'Sarina Beach','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4737, 'Sarina Range','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Seaforth','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4754, 'Septimus','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4750, 'Shoal Point','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Slade Point','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'South Mackay','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4798, 'St Helens Beach','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4737, 'Sunnyside','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'Te Kowai','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'The Leap','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4751, 'Victoria Plains','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4751, 'Walkerston','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4740, 'West Mackay','QLD', 'www.mackayregionjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (4741, 'Yalboroo','QLD', 'www.mackayregionjoblink.com.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'Albanvale','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'Albion','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3022, 'Ardeer','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3012, 'Brooklyn','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Cairnlea','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Deer Park','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'Delahey','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Delahey','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3030, 'Derrimut','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Hillside','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3036, 'Keilor','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3038, 'Keilor Downs','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3033, 'Keilor East','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3038, 'Keilor Lodge','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3036, 'Keilor North','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'Kings Park','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'St Albans','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3020, 'Sunshine','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3020, 'Sunshine North','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3020, 'Sunshine West','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Sydenham','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Taylors Hill','VIC', 'www.brimbankjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3043, 'Tullamarine','VIC', 'www.brimbankjoblink.com.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3067, 'Abbotsford','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3078, 'Alphington','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3121, 'Burnley','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3054, 'Carlton North','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3068, 'Clifton Hill','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3066, 'Collingwood','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3121, 'Cremorne ','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3078, 'Fairfield','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3065, 'Fitzroy','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3068, 'Fitzroy North','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3054, 'Princes Hill','VIC', 'www.yarrajoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3121, 'Richmond','VIC', 'www.yarrajoblink.com.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3753, 'Beveridge','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3083, 'Bundoora','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3064, 'Donnybrook','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3754, 'Doreen','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3757, 'Eden Park','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3076, 'Epping','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3757, 'Humevale','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3757, 'Kinglake West','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3075, 'Lalor','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3754, 'Mernda','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3082, 'Mill Park','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3752, 'South Morang','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3074, 'Thomastown','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3757, 'Whittlesea','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3750, 'Wollert','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3751, 'Woodstock','VIC', 'www.jobsinthenorth.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3755, 'Yan Yean','VIC', 'www.jobsinthenorth.com.au');