INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3040, 'Aberfeldie','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3042, 'Airport West','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'Albanvale','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3020, 'Albion','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3018, 'Altona','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3025, 'Altona East','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3025, 'Altona Gate','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3028, 'Altona Meadows','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3025, 'Altona North','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3022, 'Ardeer','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3032, 'Ascot Vale','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3034, 'Avondale Heights','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3019, 'Braybrook','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3338, 'Brookfield','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3012, 'Brooklyn','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Burnside','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Burnside Heights','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Cairnlea','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Calder Park','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Caroline Springs','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3030, 'Cororoc','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3041, 'Cross Keys','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Deer Park','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3022, 'Deer Park East','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Deer Park North','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Delahey','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3030, 'Derrimut','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3427, 'Diggers Rest','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3040, 'Essendon','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3041, 'Essendon Fields','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3041, 'Essendon North','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3040, 'Essendon West','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3338, 'Exford','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3338, 'Eynesbury','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3031, 'Flemington','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3011, 'Footscray','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Hillside','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Hillside','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3029, 'Hoppers Crossing','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'Kealba','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3036, 'Keilor','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3038, 'Keilor Downs','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3033, 'Keilor East','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3038, 'Keilor Lodge','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3036, 'Keilor North','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3042, 'Keilor Park','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'Kings Park','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3012, 'Kingsville','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3337, 'Kuranjang','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3028, 'Laverton','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3026, 'Laverton North','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3211, 'Little River','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3012, 'Maidstone','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3024, 'Mambourin','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3032, 'Maribyrnong','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3337, 'Melton','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3338, 'Melton South','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3337, 'Melton West','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3039, 'Moonee Ponds','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3024, 'Mount Cottrell','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3015, 'Newport','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3042, 'Niddrie','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Parwan','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3335, 'Plumpton','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3030, 'Point Cook','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3030, 'Quandong','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3023, 'Ravenhall','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3335, 'Rockbank','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3028, 'Seabrook','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3018, 'Seaholme','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3011, 'Seddon','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3015, 'South Kingsville','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3015, 'Spotswood','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3021, 'St Albans','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3041, 'Strathmore','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3041, 'Strathmore Heights','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3020, 'Sunshine','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3020, 'Sunshine North','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3020, 'Sunshine West','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Sydenham','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3029, 'Tarneit','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3037, 'Taylors Hill','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3038, 'Taylors Lakes','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3337, 'Toolern Vale','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3012, 'Tottenham','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3032, 'Travancore','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3029, 'Truganina','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3043, 'Tullamarine','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3030, 'Werribee','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3030, 'Werribee South','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3011, 'West Footscray','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3027, 'Williams Landing','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3016, 'Williamstown','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3016, 'Williamstown North','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3024, 'Wyndham Vale','VIC', 'www.melbswestjobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3013, 'Yarraville','VIC', 'www.melbswestjobs.com.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3231, 'AIREYS INLET','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'ANAKIE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3230, 'ANGLESEA','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3217, 'ARMSTRONG CREEK','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3212, 'AVALON','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3331, 'BANNOCKBURN','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3220, 'BAREENA','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'BARRABOOL','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3227, 'BARWON HEADS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'BATESFORD','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3251, 'BEEAC','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3215, 'BELL PARK','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3215, 'BELL POST HILL','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'BELLARINE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3228, 'BELLBRAE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3228, 'BELLS BEACH','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3216, 'BELMONT','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3235, 'BENWERRIN','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3231, 'BIG HILL','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3235, 'BOONAH','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3219, 'BREAKWATER','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3227, 'BREAMLEA','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'CERES','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3222, 'CLIFTON SPRINGS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3250, 'COLAC','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3227, 'CONNEWARRE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3214, 'CORIO','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3222, 'CURLEWIS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3217, 'DEAKIN UNIVERSITY','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3235, 'DEANS MARSH','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3215, 'DRUMCONDRA','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3222, 'DRYSDALE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3219, 'EAST GEELONG','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3231, 'EASTERN VIEW','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'ENFIELD','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3231, 'FAIRHAVEN','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3216, 'FRESHWATER CREEK','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'FYANSFORD','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3220, 'GEELONG','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3215, 'GEELONG NORTH','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3218, 'GEELONG WEST','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3331, 'GHERINGHAP','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'GNARWARRE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3216, 'GROVEDALE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3215, 'HAMLYN HEIGHTS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3218, 'HERNE HILL','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3216, 'HIGHTON','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3223, 'INDENTED HEAD','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3321, 'INVERLEIGH','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3228, 'JAN JUC','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3238, 'JOANNA','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3212, 'LARA','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3224, 'LEOPOLD','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3360, 'LINTON','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3232, 'LORNE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'LOVELY BANKS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3218, 'MANIFOLD HEIGHTS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3222, 'MANNERIM','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3222, 'MARCUS HILL','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3233, 'MARENGO','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3216, 'MARSHALL','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3333, 'MEREDITH','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3240, 'MODEWARRE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3231, 'MOGGS CREEK','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'MOOLAP','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3224, 'MOOLAP','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'MOORABOOL','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3240, 'MORIAC','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3216, 'MOUNT DUNEED','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3217, 'MT DUNEED','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3219, 'NEWCOMB','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3220, 'NEWTOWN','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3214, 'NORLANE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3214, 'NORTH SHORE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3226, 'OCEAN GROVE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3240, 'PARAPARAP','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3225, 'POINT LONSDALE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3212, 'POINT WILSON','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3223, 'PORTARLINGTON','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3225, 'QUEENSCLIFF','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3215, 'RIPPLESIDE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'SMYTHESDALE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3220, 'SOUTH GEELONG','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3219, 'ST ALBANS PARK','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3223, 'ST LEONARDS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'STAUGHTON VALE','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3331, 'STEIGLITZ','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3331, 'SUTHERLANDS CREEK','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3225, 'SWAN BAY','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3225, 'SWAN ISLAND','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3219, 'THOMSON','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3228, 'TORQUAY','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3221, 'WALLINGTON','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3216, 'WANDANA HEIGHTS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3217, 'WARALLILLY','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3216, 'WAURN PONDS','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3219, 'WHITTINGTON','VIC', 'www.geelongcareers.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3234, 'WYE RIVER','VIC', 'www.geelongcareers.org.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5373, 'Allendale North','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5351, 'Altona','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5353, 'Angaston','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5373, 'Bagot Well','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5460, 'Barabba','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5351, 'Barossa Goldfields','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5255, 'Belvidere','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5352, 'Bethany','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5373, 'Bethel','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Bibaringa','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Buchfelde','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Calomba','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5351, 'Cockatoo Valley','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Concordia','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5235, 'Cromer','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5355, 'Daveyston','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Dublin','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5355, 'Ebenezer','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5235, 'Eden Valley','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5116, 'Evanston','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5116, 'Evanston Gardens','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5116, 'Evanston Park','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5116, 'Evanston South','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5502, 'Fischer','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5235, 'Flaxman Valley','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5373, 'Fords','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5372, 'Freeling','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Gawler','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Gawler Belt','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Gawler East','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Gawler River','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Gawler South','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Gawler West','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5352, 'Gomersal','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5502, 'Grace Plains','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5360, 'Greenock','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5373, 'Hamilton','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Hewett','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5116, 'Hillier','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Kalbeeba','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Kangaroo Flat','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5373, 'Kapunda','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Kingsford','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5373, 'Koonunga','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5502, 'Korunye','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5352, 'Krondorf','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5115, 'Kudla','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Lewiston','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5355, 'Light Pass','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5410, 'Linwood','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Long Plains','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Lower Light','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5351, 'Lyndoch','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5400, 'Magdalla','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5502, 'Mallala','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5355, 'Marananga','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Middle Beach','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5355, 'Moppa','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5371, 'Morn Hill','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5351, 'Mount Crawford','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5235, 'Mount Pleasant','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5360, 'Nain','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5355, 'Nuriootpa','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Parham','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5353, 'Penrice','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5351, 'Pewsey Vale','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5400, 'Pinkerton Plains','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Port Gawler','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5502, 'Red Banks','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5502, 'Reeves Plains','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5350, 'Rosedale','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5371, 'Roseworthy','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5352, 'Rowland Flat','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5350, 'Sandy Creek','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5355, 'Seppeltsfield','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5371, 'Shea-Oak Log','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5235, 'Springton','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5373, 'St Johns','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5356, 'St Kitts','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5355, 'Stockwell','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5352, 'Stone Well','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5352, 'Tanunda','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5235, 'Taunton','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5371, 'Templers','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Thompson Beach','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Two Wells','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5352, 'Vine Vale','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Ward Belt','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5400, 'Wasleys','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Webb Beach','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Wild Horse Plains','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5118, 'Willaston','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5351, 'Williamstown','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5501, 'Windsor','SA', 'www.barossaplainsjobs.org.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (5400, 'Woolsheds','SA', 'www.barossaplainsjobs.org.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3056, 'Brunswick','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3057, 'Brunswick East','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3055, 'Brunswick West','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3058, 'Coburg','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3058, 'Coburg North','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3060, 'Fawkner','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3068, 'Fitzroy North','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3046, 'Glenroy','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3043, 'Gowanbrae','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3046, 'Hadfield','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3046, 'Oak Park','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3044, 'Pascoe Vale','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3044, 'Pascoe Vale South','VIC', 'www.morelandjoblink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3043, 'Tullamarine','VIC', 'www.morelandjoblink.com.au');






