USE DigitalGuidanceCounsellor;

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3078, 'Alphington','VIC', 'www.darebinjobslink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3083, 'Bundoora','VIC', 'www.darebinjobslink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3078, 'Fairfield','VIC', 'www.darebinjobslink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3086, 'La Trobe University','VIC', 'www.darebinjobslink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3085, 'Macleod','VIC', 'www.darebinjobslink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3070, 'Northcote','VIC', 'www.darebinjobslink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3072, 'Preston','VIC', 'www.darebinjobslink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3073, 'Resevoir','VIC', 'www.darebinjobslink.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3071, 'Thornbury','VIC', 'www.darebinjobslink.com.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3175, 'Dandenong','VIC', 'www.worklocalgreaterdandenong.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3175, 'Dandenong North','VIC', 'www.worklocalgreaterdandenong.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3175, 'Dandenong South','VIC', 'www.worklocalgreaterdandenong.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3173, 'Keysborough','VIC', 'www.worklocalgreaterdandenong.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3975, 'Lyndhurst','VIC', 'www.worklocalgreaterdandenong.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3174, 'Noble Park','VIC', 'www.worklocalgreaterdandenong.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3174, 'Noble Park North','VIC', 'www.worklocalgreaterdandenong.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3171, 'Springvale','VIC', 'www.worklocalgreaterdandenong.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3172, 'Springvale South','VIC', 'www.worklocalgreaterdandenong.com.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3782, 'Avonsleigh','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3981, 'Bayles','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3807, 'Beaconsfield','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3808, 'Beaconsfield Upper','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3806, 'Berwick','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3980, 'Blind Bight','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Botanic Ridge','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3815, 'Bunyip','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3815, 'Bunyip North','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3984, 'Caldermeade','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Cannons Creek','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3978, 'Cardinia','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3981, 'Catani','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3782, 'Clematis','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3978, 'Clyde','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3978, 'Clyde North','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3781, 'Cockatoo','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3814, 'Cora Lynn','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Cranbourne','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Cranbourne East','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Cranbourne North','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Cranbourne South','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Cranbourne West','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3981, 'Dalmore','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Devon Meadows','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3808, 'Dewhurst','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3177, 'Doveton','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3782, 'Emerald','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3802, 'Endeavour Hills','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3177, 'Eumemmerring','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Five Ways','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3805, 'Fountain Gate','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3814, 'Garfield','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3814, 'Garfield North','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3783, 'Gembrook','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3807, 'Guys Hill','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3803, 'Hallam','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3976, 'Hampton Park','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3806, 'Harkaway','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3981, 'Heath Hill','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3815, 'Iona','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3977, 'Junction Village','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3981, 'Koo Wee Rup','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3981, 'Koo Wee Rup North','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3984, 'Lang Lang','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3984, 'Lang Lang East','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3816, 'Longwarry','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3975, 'Lynbrook','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3975, 'Lyndhurst','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3156, 'Lysterfield South','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3812, 'Maryknoll','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3159, 'Menzies Creek','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3816, 'Modella','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3984, 'Monomeith','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3781, 'Mount Burnett','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3781, 'Nangana','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3812, 'Nar Nar Goon','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3812, 'Nar Nar Goon North','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3805, 'Narre Warren','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3804, 'Narre Warren North','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3805, 'Narre Warren South','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3987, 'Nyora','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3809, 'Officer','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3809, 'Officer South','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3810, 'Pakenham','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3810, 'Pakenham South','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3810, 'Pakenham Upper','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3912, 'Pearcedale','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3810, 'Rythdale','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3984, 'Tenby Point','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3815, 'Tonimbuk','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3980, 'Tooradin','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3813, 'Tynong','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3813, 'Tynong North','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3814, 'Vervale','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3980, 'Warneet','VIC', 'www.caseycardiniajobs.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3981, 'Yannathan','VIC', 'www.caseycardiniajobs.com.au');

INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Addington','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Adelaide Lead','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Alfredton','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Allendale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Alma','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Amherst','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Ascot','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Bacchus Marsh','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Bakery Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Bald Hills','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Ballan','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Ballarat','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Ballarat Central','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Ballarat East','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Ballarat North','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Ballarat Roadside Delivery','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Ballarat West','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Balliang','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Balliang East','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3333, 'Bamganie','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Barfold','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Barkers Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Barkly','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Barkstead','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'Barrys Reef','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3460, 'Basalt','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Baynton','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Baynton East','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Beaufort','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Beremboke','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Berringa','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Black Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'Blackwood','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Blakeville','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Blampied','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Blowhard','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Bo Peep','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Bolwarrah','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Bonshaw','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Bowenvale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3361, 'Bradvale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Brewster','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Broomfield','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Brown Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Bullarook','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Bullarto','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Bullarto South','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Bunding','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Bung Bong','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3334, 'Bungal','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Bungaree','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3357, 'Buninyong','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Bunkers Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Burnbank','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Burrumbeet','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Cabbage Tree','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Cambrian Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Campbells Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Campbelltown','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Canadian','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Cape Clear','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Caralulup','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Cardigan','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Cardigan Village','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3334, 'Cargerie','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Carngham','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3361, 'Carranballac','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Chapel Flat','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Chepstowe','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Chewton','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Chewton Bushlands','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Chute','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Clarendon','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Claretown','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Clarkes Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3370, 'Clunes','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Clydesdale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Coghills Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Coimadai','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Colbrook','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Concongella','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Coomoora','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Corindhap','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Cotswold','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Craigie','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3363, 'Creswick','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3363, 'Creswick North','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Cross Roads','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Daisy Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3341, 'Dales Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Darley','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3460, 'Daylesford','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3363, 'Dean','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3356, 'Delacombe','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Denver','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Dereel','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3478, 'Dooboobetic','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Drummond','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Dry Diggings','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Dunach','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3352, 'Dunnstown','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Durdidwarrah','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Edgecombe','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Eganstown','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3334, 'Elaine','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Elevated Plains','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3469, 'Elmhurst','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Eureka','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Evansford','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Faraday','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'Fern Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Fiskville','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Flagstaff','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Franklinford','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Frenchmans','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Fryerstown','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3363, 'Glendaruel','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Glendonald','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3370, 'Glengower','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Glenhope','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3469, 'Glenlofty','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3469, 'Glenlogie','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Glenluce','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Glenlyon','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Glenmore','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3469, 'Glenpatrick','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Golden Point','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Golden Point','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Golden Point','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3345, 'Gordon','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Gower','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3341, 'Greendale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Greenhill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Guildford','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Haddon','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3360, 'Happy Valley','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Havelock','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Hepburn','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Hepburn Springs','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Hillcrest','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Homebush','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Hopetoun Park','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Illabarook','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Ingliston','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Invermay Park','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Irishtown','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Joel Joel','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Joel South','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Joyces Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Kingston','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Kooroocheang','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3341, 'Korobeit','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Korweinguboora','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Kyneton','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Kyneton South','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Lake Bolac','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3355, 'Lake Gardens','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Lake Goldsmith','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Lake Wendouree','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Lake Wongan','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Landsborough','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Landsborough West','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3363, 'Langdons Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Langley','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Lauriston','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Lawrence','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Leonards Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'Lerderderg','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Lillicur','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3360, 'Linton','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'Little Hampton','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Long Forest','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Lucas','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Lyal','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Lyonville','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Maddingley','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Main Lead','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Majorca','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3360, 'Mannibadar','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Maryborough','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Mckenzie Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3478, 'Medlyn','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Mena Park','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3333, 'Meredith','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Merrimu','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Metcalfe East','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Mia Mia','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Mininera','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3355, 'Mitchell Park','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Moolort','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3478, 'Moonambel','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Moonlight Flat','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3334, 'Morrisons','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3363, 'Mount Beckworth','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3370, 'Mount Cameron','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Mount Clear','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3334, 'Mount Doran','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Mount Emu','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Mount Franklin','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Mount Glasgow','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Mount Helen','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Mount Pleasant','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Mount Prospect','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3342, 'Mount Wallace','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Muckleford','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Musk','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Musk Vale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3341, 'Myrniong','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Natte Yallock','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Navarre','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Nerrin Nerrin','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Nerrina','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Nerring','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'Newbury','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3350, 'Newington','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Newlyn','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Newlyn North','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Newtown','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Nintingbool','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'North Blackwood','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3469, 'Nowhere Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Parwan','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Pastoria','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Pastoria East','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3341, 'Pentland Hills','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3478, 'Percydale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Piggoreet','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Pipers Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Pitfield','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3360, 'Pittong','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3461, 'Porcupine Ridge','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Raglan','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Rathscar','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Rathscar West','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Red Lion','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Redesdale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Rocklyn','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Rokewood Junction','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Ross Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Rowsley','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Scarsdale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3356, 'Sebastopol','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Sidonia','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3465, 'Simson','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3361, 'Skipton','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Smeaton','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3364, 'Smokeytown','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3351, 'Smythes Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Spring Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3478, 'St Arnaud','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3340, 'Staughton Vale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Stockyard Hill','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Stoneleigh','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Stony Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3371, 'Talbot','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3478, 'Tanwood','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Tarilta','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3363, 'Tourello','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Trawalla','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'Trentham','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3458, 'Trentham East','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Tulkara','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3444, 'Tylden','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3370, 'Ullina','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Vaughan','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3478, 'Warrenmang','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3373, 'Waterloo','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3384, 'Wattle Creek','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3355, 'Wendouree','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3355, 'Wendouree Village','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3360, 'Willowvale','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3451, 'Yapeen','VIC', 'www.cyba.com.au');
INSERT INTO PostCode (PostCodeValue, Suburb, State, SiteUrl) VALUES (3478, 'Yawong Hills','VIC', 'www.cyba.com.au');






